name: jupyterlite-emscripten-forge
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/emscripten-forge-4x
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - scikit-learn
  - pyarrow
  - pandas
  - matplotlib-base
  - plotly
